### ISSUE TITLE
.gitsubprojects does not reference to master

### ISSUE THREAD

**Issue by cnowke** [HBPVIS/zeq#102] opened 2015-10-21 11:28 UTC
In order to pull the latest changes in the master ZeroBuf within zeq, I needed to change the .gitsubprojects to:
git_subproject(ZeroBuf https://github.com/HBPVIS/ZeroBuf.git master).
Is there a reason on why specific versions are pulled here instead of the most current source?

**Comment by hernando** [comment] 2015-10-21 14:47
In principle, zeq (as any other project using the same approach) pulls the ZeroBuf version which is known to compile and work for it. Since master is a moving reference, there's no guarantee that using it will always work. Furthermore, having master makes it very hard (sometimes impossible, depending on the project) to build previous versions, something that is necessary for reproducing results or git bisect regressions. This is also a decision that will facilitate continuous deployment.

**Comment by eile** [comment] 2015-10-21 15:10
```ninja update && ninja rebase``` will bring everything up to date. As @hernando said, your build might not work afterwards.

**Comment by cnowke** [comment] 2015-10-21 15:17
Ah, good to know. Forgive my git ignorance, I will soon be up to date with the git workflow. Thanks anyway!

**Comment by eile** [comment] 2015-10-21 15:50
No worries. Closing ticket.

**Closed by eile** 2015-10-21 15:50 UTC
